# Generated by Django 3.2.5 on 2021-12-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_launch', models.DateField()),
                ('date_due', models.DateField()),
                ('nature', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=400)),
                ('assign_sub', models.FileField(upload_to='files/assign/submission')),
                ('state', models.TextField(choices=[('valid', 'Valid'), ('NotValid', 'Not Valid')], max_length=60)),
                ('eva_grade', models.FloatField()),
                ('eva_comm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nb_student', models.IntegerField()),
                ('group_mail', models.EmailField(max_length=200)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.ManyToManyField(to='students.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True)),
                ('content', models.TextField(max_length=600)),
                ('type', models.TextField(choices=[('valid', 'Valid'), ('NotValid', 'Not Valid')], max_length=60)),
                ('group', models.ManyToManyField(to='students.Group')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.TextField(blank=True, max_length=400)),
                ('justif', models.FileField(blank=True, max_length=400, upload_to='students/justif')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('prof_mail', models.EmailField(max_length=200)),
                ('perso_mail', models.EmailField(max_length=200)),
                ('due', models.IntegerField()),
                ('picture', models.ImageField(upload_to='files/teachers/img')),
                ('modules', models.ManyToManyField(to='students.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_start', models.TimeField()),
                ('h_end', models.TimeField()),
                ('is_online', models.BooleanField(default=False)),
                ('room_number', models.IntegerField(blank=True)),
                ('goal', models.TextField(max_length=400)),
                ('synopsis', models.TextField(max_length=400)),
                ('logistics', models.TextField(blank=True, max_length=400)),
                ('gender', models.CharField(choices=[('regular', 'Regular'), ('remedial', 'Remedial'), ('support', 'Support'), ('training', 'Training')], max_length=60)),
                ('records', models.ManyToManyField(to='students.Records')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='sessions',
            field=models.ManyToManyField(to='students.Session'),
        ),
        migrations.AddField(
            model_name='module',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(to='students.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.ManyToManyField(to='students.State'),
        ),
    ]
