# Generated by Django 3.2.5 on 2021-12-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20211215_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname', 'firstname']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='assign',
            name='assign_doc',
            field=models.FileField(blank=True, upload_to='files/assign/assignment'),
        ),
        migrations.AddField(
            model_name='assign',
            name='group',
            field=models.ManyToManyField(to='students.Student'),
        ),
        migrations.AddField(
            model_name='assign',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.module'),
        ),
        migrations.AddField(
            model_name='state',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='situation',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('repeating', 'Repeating'), ('derogatory', 'Derogatory'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='state_choice',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excluded', 'Excluded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.ManyToManyField(blank=True, null=True, to='students.State'),
        ),
    ]
