# Generated by Django 3.2.5 on 2021-12-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20211215_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='group',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='students.Teacher'),
        ),
        migrations.AlterField(
            model_name='module',
            name='group',
            field=models.ManyToManyField(blank=True, to='students.Group'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='students.Session'),
        ),
        migrations.AlterField(
            model_name='records',
            name='group',
            field=models.ManyToManyField(blank=True, to='students.Group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='modules',
            field=models.ManyToManyField(blank=True, to='students.Module'),
        ),
    ]
