# Generated by Django 3.2.5 on 2021-12-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211215_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='session',
            name='records',
        ),
        migrations.AddField(
            model_name='records',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.module'),
        ),
        migrations.AlterField(
            model_name='session',
            name='gender',
            field=models.CharField(choices=[('regular', 'Regular'), ('remedial', 'Remedial'), ('support', 'Support'), ('training', 'Training')], max_length=60, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='h_end',
            field=models.TimeField(verbose_name='Ending Time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='h_start',
            field=models.TimeField(verbose_name='Starting Time'),
        ),
    ]
