# Generated by Django 3.2.5 on 2021-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20211215_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
